
services:
  app:
    build: .
    network_mode: "host"
    volumes:
      - /home/archit-anand/My-AI-data:/app/backend/data
    secrets:
      - DATA_DIR
      - APP_PASSWORD
      - LM_STUDIO_URL
      - LM_STUDIO_API_KEY
      - TAVILY_API_KEY

secrets:
  # Defining secrets mapped to files in the ./secrets directory
  DATA_DIR:
    file: ./secrets/DATA_DIR
  APP_PASSWORD:
    file: ./secrets/APP_PASSWORD
  LM_STUDIO_URL:
    file: ./secrets/LM_STUDIO_URL
  LM_STUDIO_API_KEY:
    file: ./secrets/LM_STUDIO_API_KEY
  TAVILY_API_KEY:
    file: ./secrets/TAVILY_API_KEY
