
services:
  app:
    build: .
    networks:
      - secure-internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - tavily_mcp
      - playwright_mcp
    volumes:
      - /home/archit-anand/docker-data/shared/My-AI-data:/app/backend/data
    environment:
      - TZ=Asia/Kolkata
    secrets:
      - DATA_DIR
      - APP_PASSWORD
      - AI_URL
      - AI_API_KEY
      - TAVILY_API_KEY
      - MCP_API_KEY
      - PLAYWRIGHT_MCP_API_KEY

  bastion_ssh:
    build:
      context: .
      dockerfile: Dockerfile.bastion
    container_name: bastion_ssh
    volumes:
      - ./secrets/authorized_keys:/home/appuser/.ssh/authorized_keys:ro
    ports:
      - 2222:2222
    networks:
      - secure-internal
    restart: unless-stopped

  tavily_mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: tavily_mcp
    networks:
      - secure-internal
    environment:
      - TZ=Asia/Kolkata
    secrets:
      - TAVILY_API_KEY
      - MCP_API_KEY
    restart: unless-stopped

  playwright_mcp:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    container_name: playwright_mcp
    networks:
      - secure-internal
    environment:
      - TZ=Asia/Kolkata
    secrets:
      - PLAYWRIGHT_MCP_API_KEY
    restart: unless-stopped

networks:
  secure-internal:
    driver: bridge

secrets:
  # Defining secrets mapped to files in the ./secrets directory
  DATA_DIR:
    file: ./secrets/DATA_DIR
  APP_PASSWORD:
    file: ./secrets/APP_PASSWORD
  AI_URL:
    file: ./secrets/AI_URL
  AI_API_KEY:
    file: ./secrets/AI_API_KEY
  TAVILY_API_KEY:
    file: ./secrets/TAVILY_API_KEY
  MCP_API_KEY:
    file: ./secrets/MCP_API_KEY
  PLAYWRIGHT_MCP_API_KEY:
    file: ./secrets/PLAYWRIGHT_MCP_API_KEY
